### ISSUE TITLE
Entity and null value

### ISSUE THREAD

**Issue by GoogleCodeExporter** [danieleteti/delphi-orm#38]
```
how do I map a property of an entity to accept null value?
```

Original issue reported on code.google.com by `evieira...@gmail.com` on 27 Mar 2014 at 5:26

**Comment by danieleteti** [comment]
Currently there is some "support for null".
It is not a real null handling. It is just a "convestion" over the types.
So, you can decide that if a TDate is 0 then that value should be considered as null.

Check the unit tests.
